# @package _global_
type: model

# Bigram Model

model:
  _target_: brainle.models.text_model.TextModelDict
  learning_rate: 1e-3
  model:
    _target_: brainle.models.architectures.grams.BigramNet
    vocabulary_size: 837
    num_features: 16
    num_tokens: 12
    num_nodes: 6
    num_layers: 1

datamodule:
  _target_: brainle.datamodules.wikitext_datamodule.WikiTextDatamodule
  train_val_split: [906742, 1000]
  batch_size: 2048
  num_workers: 0
  block_size: 12
  p_word_mask: 0.0
  p_char_mask: 0.0

callbacks:
  rich_progress_bar:
    _target_: pytorch_lightning.callbacks.RichProgressBar

  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "valid_loss"   # name of the logged metric which determines when model is improving
    save_top_k: 1           # save k best models (determined by above metric)
    save_last: True         # additionaly always save model from last epoch
    mode: "min"             # can be "max" or "min"
    verbose: False
    dirpath: ${logs_dir}/ckpts/${now:%Y-%m-%d-%H-%M-%S}
    filename: '{epoch:02d}-{valid_loss:.3f}'

  model_summary:
    _target_: pytorch_lightning.callbacks.RichModelSummary
    max_depth: 2

  text_logger:
    _target_: brainle.callbacks.text_callback.BigramLogger
    batch_frequency: 800


loggers:
  wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    project: ${oc.env:WANDB_PROJECT}
    entity: ${oc.env:WANDB_ENTITY}
    # offline: False  # set True to store all logs only locally
    job_type: "train"
    group: ""
    save_dir: ${logs_dir}

trainer:
  _target_: pytorch_lightning.Trainer
  gpus: 0 # Set `1` to train on GPU, `0` to train on CPU only, and `-1` to train on all GPUs, default `0`
  log_gpu_memory: all # Logs memory of GPUs, default `None`
  precision: 32 # Precision used for tensors, default `32`
  accelerator: null # `ddp` GPUs train individually and sync gradients, default `None`
  min_epochs: 1
  max_epochs: 100_000
  enable_model_summary: False
  log_every_n_steps: 1 # Logs metrics every N batches
